name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  test:
    name: ${{ matrix.version == '1' && 'stable' || 'nightly' }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        version: ['1', 'nightly']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: xvfb-run
